### ISSUE TITLE
Netlify set up for Quarto

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/austraits.org#23]
@dfalster following the [Quarto documentation](https://quarto.org/docs/publishing/netlify.html#publish-command)

I require an Netilfy ID and URL to publish our Quarto website in the following format: 

```
- source: project
  netlify:
    - id: "5f3abafe-68f9-4c1d-835b-9d668b892001"
      url: "https://tubular-unicorn-97bb3c.netlify.app"
```

Would you be able to retrieve these for me? This will supplement the #22 PR! Thanks!
